### ISSUE TITLE
S3 backend

### ISSUE THREAD

**Issue by obeyler** [helm/chartmuseum#162]
#8 issue add a way to declare new endpoint for S3 storage such as minio.
My trouble is that my minio use a self signed certificate. Does a way exist to add new CA or disable SSL check ?

**Comment by jdolitsky** [comment]
@obeyler sorry for late response. I'm not seeing a way to add custom CA (looking at [s3 config options](https://github.com/aws/aws-sdk-go/blob/56018901efd0b8084af1fb83b7e2604aba53f143/aws/config.go#L33)). We may be able to specify a custom `HTTPClient`?

However, if you specify a `--storage-amazon-endpoint` with `http://` vs `https://` the `DisableSSL` param will be set to false.

@freemantle1989 yes Minio is supported, although if using self-signed cert only w http apparently right now. Just use the `--storage-amazon-endpoint` option.

**Comment by freemantle1989** [comment]
i am trying it like:
chartmuseum --debug --port=8080 --storage="amazon" --storage-amazon-bucket="MY_BUCKET" --storage-amazon-endpoint="http://MY_MINIO:9000" --storage-amazon-prefix="MY_PREFIX"

and i allways get this:
ERROR   NoCredentialProviders: no valid providers in chain. Deprecated.

..i can change prefix an bucket but it has the same result.....i also tried it without prefix and bucket but got the same result

Do i have to give chartmuseum the minio credentials? I dont see a way to do that..

**Comment by obeyler** [comment]
Is there a way to specify witch kind of signature must be used ?
I have a S3 with V2 signature and not V4

**Comment by romil-punetha** [comment]
I get the same error as @freemantle1989. Im using it on eks. No minio. Anyone having any solutions for this? My chart values looks like:
```
replicaCount: 1
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
image:
  repository: chartmuseum/chartmuseum
  tag: v0.8.2
  pullPolicy: IfNotPresent
env:
  open:
    STORAGE: amazon
    STORAGE_AMAZON_BUCKET: prod-eks-cloudformation-template
    STORAGE_AMAZON_PREFIX: 
    STORAGE_AMAZON_REGION: ap-south-1
  secret:
    BASIC_AUTH_USER: xxxxx
    BASIC_AUTH_PASS: xxxxxxxxx
```

**Comment by hack3d** [comment]
I got it work with minio in kubernetes. My configmap looks like:
```
metadata:
  name: chartmuseum-configmap
  namespace: chartmuseum
data:
  AUTH_ANONYMOUS_GET: 'true'
  BASIC_AUTH_USER: pchartmuseum
  DEPTH: '2'
  STORAGE: amazon
  STORAGE_AMAZON_BUCKET: chartmuseum
  STORAGE_AMAZON_ENDPOINT: 'http://chartmuseum-s3-minio:80'
  STORAGE_AMAZON_PREFIX: ''
kind: ConfigMap
```

The Secret looks like:
```
metadata:
  name: secret-chartmuseum
  namespace: chartmuseum
data:
  AWS_ACCESS_KEY_ID: XXXXXXX
  AWS_SECRET_ACCESS_KEY: XXXXXXXX
type: Opaque
kind: Secret
```
You have to create the bucket manually or with a post-install / post-upgrade job.

The deployment is configured like this:
```
spec:
      containers:
        - name: chartmuseum
          image: 'chartmuseum/chartmuseum:v0.12.0'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: secret-chartmuseum
            - configMapRef:
                name: chartmuseum-configmap
          resources:
            limits:
              cpu: '1'
              memory: 5Gi
            requests:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
```

I hope it's helpful for you guys. We will see how it performs in production.
