### ISSUE TITLE
Image v0.8.2: container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by RGPosadas** [helm/chartmuseum#244]
**Problem**
Even though https://github.com/helm/chartmuseum/pull/167 fixes the `container has runAsNonRoot and image will run as root` error, it doesn't work when PSPs are enabled and it gives the same error.

Here is our PSP:
```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: z-default-restrictive-psp
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  privileged: false
  allowPrivilegeEscalation: false
  hostNetwork: false
  allowedCapabilities:
    - 'IPC_LOCK'
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  volumes:
    - 'secret'
    - 'emptyDir'
    - 'configMap'
    - 'projected'
    - 'downwardAPI'
    - 'gcePersistentDisk'
    - 'persistentVolumeClaim'
```

**Our attempts at a fix**
1. We set `securityContext: {}` in the `values.yaml` file, however the pod was still brought up with:
```
  securityContext:
    fsGroup: 1000
    supplementalGroups:
    - 1
```
which did not fix the problem.

2. We actually were able to fix the `container has runAsNonRoot and image will run as root` error by changing the `chartmuseum` user to `1001` instead of `1000` in the Dockerfile.
