### ISSUE TITLE
error: failed to download 

### ISSUE THREAD

**Issue by schizoid90** [helm/chartmuseum#302]
Chart museum version: 0.11.0
Helm version: 3.0.0

I have chartmuseum installed via helm and pushing charts via an automated Jenkins job. The charts are created OK and I can download them manually (using curl) but when I run helm install, I get a failed to download error.

**my index.yaml**
```
curl -k "https://helm.domain.lan/index.yaml"
apiVersion: v1
entries:
  chartmuseum:
  - apiVersion: v2
    appVersion: 0.11.0
    created: "2019-12-19T09:01:53.814801067Z"
    dependencies:
    - name: chartmuseum
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 2.6.0
    description: Repository for helm charts
    digest: 1b89b64fd8ba654db3defcb40c759f332ef30578b9ffe5c2bf2cf82a70d030b1
    name: chartmuseum
    urls:
    - https://helm.domain.lan/charts/chartmuseum-0.1.8.tgz
    version: 0.1.8
  elk:
  - apiVersion: v2
    appVersion: 7.5.0
    created: "2019-12-19T09:01:53.862800913Z"
    dependencies:
    - name: elasticsearch
      repository: https://helm.elastic.co
      version: 7.5.0
    - name: logstash
      repository: https://helm.elastic.co
      version: 7.5.0
    - name: kibana
      repository: https://helm.elastic.co
      version: 7.5.0
    - name: filebeat
      repository: https://helm.elastic.co
      version: 7.5.0
    description: Centralised Logging Platform
    digest: 76ac94a2781b0fbf1181f84a2962999f4e2652caeab8bd2b9e1812a65dfbaaca
    name: elk
    urls:
    - https://helm.domain.lan/charts/elk-0.1.3.tgz
    version: 0.1.3
  prometheus:
  - apiVersion: v2
    appVersion: 2.13.1
    created: "2019-12-19T08:46:02.357794989Z"
    dependencies:
    - name: prometheus
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 9.5.1
    description: Metrics monitor for K8s
    digest: 87a19cee3a68002ed623ab50a2d049148934eef2a0cfffb5771df4d6a1ea3efc
    name: prometheus
    urls:
    - https://helm.domain.lan/charts/prometheus-0.1.10.tgz
    version: 0.1.10
generated: "2019-12-19T09:01:56Z"
serverInfo: {}
```

**api/charts/**
```
curl -k "https://helm.domain.lan/api/charts"
{
  "chartmuseum": [
    {
      "name": "chartmuseum",
      "version": "0.1.8",
      "description": "Repository for helm charts",
      "apiVersion": "v2",
      "appVersion": "0.11.0",
      "dependencies": [
        {
          "name": "chartmuseum",
          "version": "2.6.0",
          "repository": "https://kubernetes-charts.storage.googleapis.com"
        }
      ],
      "urls": [
        "https://helm.domain.lan/charts/chartmuseum-0.1.8.tgz"
      ],
      "created": "2019-12-19T09:01:53.814801067Z",
      "digest": "1b89b64fd8ba654db3defcb40c759f332ef30578b9ffe5c2bf2cf82a70d030b1"
    }
  ],
  "elk": [
    {
      "name": "elk",
      "version": "0.1.3",
      "description": "Centralised Logging Platform",
      "apiVersion": "v2",
      "appVersion": "7.5.0",
      "dependencies": [
        {
          "name": "elasticsearch",
          "version": "7.5.0",
          "repository": "https://helm.elastic.co"
        },
        {
          "name": "logstash",
          "version": "7.5.0",
          "repository": "https://helm.elastic.co"
        },
        {
          "name": "kibana",
          "version": "7.5.0",
          "repository": "https://helm.elastic.co"
        },
        {
          "name": "filebeat",
          "version": "7.5.0",
          "repository": "https://helm.elastic.co"
        }
      ],
      "urls": [
        "https://helm.domain.lan/charts/elk-0.1.3.tgz"
      ],
      "created": "2019-12-19T09:01:53.862800913Z",
      "digest": "76ac94a2781b0fbf1181f84a2962999f4e2652caeab8bd2b9e1812a65dfbaaca"
    }
  ],
  "prometheus": [
    {
      "name": "prometheus",
      "version": "0.1.10",
      "description": "Metrics monitor for K8s",
      "apiVersion": "v2",
      "appVersion": "2.13.1",
      "dependencies": [
        {
          "name": "prometheus",
          "version": "9.5.1",
          "repository": "https://kubernetes-charts.storage.googleapis.com"
        }
      ],
      "urls": [
        "https://helm.domain.lan/charts/prometheus-0.1.10.tgz"
      ],
      "created": "2019-12-19T08:46:02.357794989Z",
      "digest": "87a19cee3a68002ed623ab50a2d049148934eef2a0cfffb5771df4d6a1ea3efc"
    }
  ]
}
```

**search repo**
```
helm search repo myrepo
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
myrepo/chartmuseum    0.1.8           0.11.0          Repository for helm charts
myrepo/elk            0.1.3           7.5.0           Centralised Logging Platform
myrepo/prometheus     0.1.10          2.13.1          Metrics monitor for K8s
```

**helm install**
```
helm install -n monitoring prometheus myrepo/prometheus
Error: failed to download "myrepo/prometheus" (hint: running `helm repo update` may help)
```
helm repo update does not help

Is there something I'm doing wrong here?

I added the "CHART_URL" environment variable to chart URLs as the same behavior existed without it as well
