### ISSUE TITLE
Auto-purge, get rid of old chart versions

### ISSUE THREAD

**Issue by jdolitsky** [helm/chartmuseum#316]
Add feature flags that enable auto-removal of old chart versions in storage based on various age / last used / version parameters

**Comment by cep21** [comment]
I'm interested in this ticket.  It's something I could do out of band, but the missing piece is I don't think there's anything in chartmuseum that tracks last used for charts.  Does this data currently exist?  If we were to add it, where would it be stored?

**Comment by scbizu** [comment]
@cep21 Happy with your interests , maybe [this](https://github.com/chartmuseum/storage/blob/main/storage.go#L32) is what you find ? If you can help us with this feature , it will make a big sense :)

**Comment by cep21** [comment]
@scbizu I think "last read" makes more sense than "last modified", right?  You would want to remove charts people are no longer downloading, for example.

**Comment by scbizu** [comment]
@cep21 You're right ,  but the storage itself do not support the last read timestamp yet . It will be huge PR if we add a new mechanism to the storage structure , we should handle every REQ from `helm pull`, and update the last read timestamp. 

I think this is why this issue still tag with `help wanted` XD

**Comment by cep21** [comment]
One idea is to store this information inside redis, for example.  Another is to use the backend storage itself to store this information and "sync" some kind of ledger every 60 seconds (for example).

**Comment by scbizu** [comment]
Maybe the AutoPurge should be provided as an interface function , and it can be differ from the real storage backends. The expiration duration should be configurable if users open the auto purge feature .

**Comment by cep21** [comment]
> and "sync" some kind of ledger every 60 seconds 

This could be tricky if people are running multiple chartmuseum instances for redundancy, since we'll have to merge ledgers

**Comment by vadasambar** [comment]
It'd be great if we could have more than one conditions to decide whether to delete the charts or not. E.g., Instead of "Delete all the charts older than 2 months", it would be better if we have "Delete all the charts older than 2 months matching a particular regex". This is because you might not want to delete release (e.g., `2.1.0`) charts but if you want to delete pre-release charts (e.g., `2.1.0-custom-fix` or `2.1.0-pr-3245`), you could use regex to match all the pre-release charts older than specified time period (Check #383 ). 

However, one thing that concerns me about regex is you'd want to test it out first to see which charts would be deleted with that particular regex to avoid deleting charts you didn't intend to delete.

**Comment by scbizu** [comment]
The thread is too long to track information now . And let me draw the conclusion till now , the key points list below:

* Purge according to the `last read`(or can be fallback to `last modified` ?)
* Should solve the multi-tenants problem (purge one tenant should not affect others) <- need further discussions now
* Purge supports some conditions (e.g.: regex rules)
* Optional: should provide a flag to determine whether users need to **soft delete** the chart. (**soft delete** here means not really purges the chart but logs the will-be-purged charts)

Any other updates ? @cep21 @vadasambar

**Comment by cep21** [comment]
Above looks right.  Bullet (3) is probably an enhancement off the core request: bullet (1).  Also the difference between `last read` and `last modified` is pretty huge in both use and ease-of-implementation.

**Comment by vadasambar** [comment]
>Optional: should provide a flag to determine whether users need to soft delete the chart. (soft delete here means not really purges the chart but logs the will-be-purged charts)
Nitpick: I think it'd be better to call it `dry-run` instead. `soft delete` makes me think that the chart would be archived or removed from the index but the data would still be there but what we want to show using `soft delete` (as far as I've understood) is what's going to be deleted if you run a delete operation. 

Everything else looks good to me @scbizu

**Comment by scbizu** [comment]
Can we describe our config file as below (YAML): 

```yaml
enable: true
tenants:
 # address your tenants here
 # if the tenant name not match or even not set
 # the purge rule will not be applied
 mydomain.com:
   conditions:
   - key: ChartName/ChartVersion/ChartLastModified
     rules:
     # specify the rule that which kinds of chart should be purged
     - operator: neq/eq/gt(timestamp/version only)/lt(timestamp/version only)/regex
       rule: "v1.0.0"
 mydomain.com/other:
   conditions:
   - key: ChartLastModified
     rules:
     - operator: lt
       rule: 1613289713

```
