### ISSUE TITLE
Can't list charts when running on Kubernetes

### ISSUE THREAD

**Issue by davidfm** [helm/chartmuseum#353]
Hello,

I've repo of this structure running using S3 for storage.

```
charts
├── repoa
│   └── mychart-0.1.0.tgz
```

I've just initialized so it's only got 1 repo, and 1 chart. Eventually there will be several repos.

I first tested this running on docker. The docker command I used is:

```
docker run -e DEPTH=1  -e STORAGE=amazon -e STORAGE_AMAZON_BUCKET=bucketName -e STORAGE_AMAZON_PREFIX="charts/" -e STORAGE_AMAZON_REGION=eu-west-1 -e AWS_ACCESS_KEY_ID=awsAccessKey -e AWS_SECRET_ACCESS_KEY=awsSecretKey -p 8080:8080 chartmuseum/chartmuseum:latest
```
Running this works perfectly:

```
helm repo add test http://localhost:8080/repoa
helm search mychart
curl localhost:8080/repoa/api/charts
```   

Each of those commands work as expected. However, I also deployed it on a Kubernetes cluster using the Helm chart.

These two commands work fine
```
helm repo add test https://chartmusem.mydomain.com/repoa
helm search mychart
```

However curling `https://chartmuseum.mydomain.com/repoa/api/charts` returns `{"error":"not found"}`

This is my values file. Is there something I might've configured incorrectly here?

```
ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
    hosts:
    -   name: chartmuseum.mydomain.com
        path: /
        tls: true
        tlsSecret: chartmuseum-secret
env:
    open:
        STORAGE: amazon
        STORAGE_AMAZON_BUCKET: bucketName
        STORAGE_AMAZON_PREFIX: charts/
        STORAGE_AMAZON_REGION: eu-west-1
        DEPTH: 1
    secret:
        AWS_ACCESS_KEY_ID: awsAccessKeyId
        AWS_SECRET_ACCESS_KEY: awsSecretAccessKey

```

Thanks.

**Comment by scbizu** [comment]
repo tests works fine means your `https://chartmusem.mydomain.com/repoa/index.yaml` looks good .  AFAK, your `path` will match  `/charts` rather than `/api/charts` that U expects , and then results with `not found` . You can use [nginx ingress's rewrite-root](https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/rewrite) to solve your problem.

Hope this can help U  :)

**Comment by jdolitsky** [comment]
Hi, the Helm chart uses values.yaml which sets DISABLE_API=true by default: https://github.com/helm/charts/blob/master/stable/chartmuseum/values.yaml#L74

You probably need to add this to you values file:

```
env:
    open:
        # disable all routes prefixed with /api
        DISABLE_API: false

        # allow anonymous GET operations when auth is used
        AUTH_ANONYMOUS_GET: true

        . . .
```
