### ISSUE TITLE
Secret  creation and existingSecret

### ISSUE THREAD

**Issue by michelefa1988** [helm/chartmuseum#359]
**Problem**
It seems that we are unable to grab certain credentials (e.g Azure credentials) from an existingSecret and at the same time create a secret on helm chart deployment for other secrets which do not exist (e.g BASIC_AUTH_USER and BASIC_AUTH_PASS)

**Expected Criteria**
The YAML below will use chartmuseum-azstorage-secret for secrets but authentication will be enabled for the given username and password. 
```
secret:
    BASIC_AUTH_USER: myUserName
    BASIC_AUTH_PASS: mySecurePassword
  existingSecret: chartmuseum-azstorage-secret
  # Stores Enviromnt Variable to secret key name mappings
  existingSecretMappings:
    AZURE_STORAGE_ACCOUNT:  AZURE_STORAGE_ACCOUNT
    AZURE_STORAGE_ACCESS_KEY:  AZURE_STORAGE_ACCESS_KEY`
```

**Current Bug**
Deploying the YAML below will mount the secret mapping but the BASIC_AUTH_USER and BASIC_AUTH_PASS will be ignored.
