### ISSUE TITLE
Panic when restarting chartmuseum on Kubernetes

### ISSUE THREAD

**Issue by wbrefvem** [helm/chartmuseum#442]
This may be a duplicate of #401.

I'm running ChartMuseum on AKS. I recently upgraded my cluster from k8s 1.17 to 1.18 (and then subsequently to 1.19), and when the chartmuseum pod came back up, it crashed with this message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1be5e33]

goroutine 1 [running]:
helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).getIndexFile(0xc0000ce900, 0xc0005c9a10, 0x0, 0x0, 0xc000a06380, 0xc000a063c0)
	/go/src/github.com/helm/chartmuseum/pkg/chartmuseum/server/multitenant/index.go:43 +0x93
helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).primeCache(0xc0000ce900, 0xc0004b1b90, 0x5)
	/go/src/github.com/helm/chartmuseum/pkg/chartmuseum/server/multitenant/cache.go:87 +0x85
helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.NewMultiTenantServer(0xc0000e60b8, 0xc0000cd290, 0x24cc558, 0xc0005c9920, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00005201b, ...)
	/go/src/github.com/helm/chartmuseum/pkg/chartmuseum/server/multitenant/server.go:147 +0x2d5
helm.sh/chartmuseum/pkg/chartmuseum.NewServer(0x24cc558, 0xc0005c9920, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/helm/chartmuseum/pkg/chartmuseum/server.go:123 +0x538
main.cliHandler(0xc00055e420)
	/go/src/github.com/helm/chartmuseum/cmd/chartmuseum/main.go:107 +0xd35
github.com/urfave/cli.HandleAction(0x1da9ba0, 0x2228110, 0xc00055e420, 0xc00055e420, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:526 +0x59
github.com/urfave/cli.(*App).Run(0xc000170540, 0xc00018c000, 0x2, 0x2, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:286 +0x675
main.main()
	/go/src/github.com/helm/chartmuseum/cmd/chartmuseum/main.go:51 +0x1c5
```

At that time, I had version 2.15.0 of the helm chart installed, with version 0.12.0 of ChartMuseum. I upgraded to version 3.1.0 of the chart (0.13.1 of ChartMuseum) and the issue persists. I'm using Azure Blob Storage as a backend. My Azure Blob Storage container appears to have an (empty) `index-cache.yaml` but no `index.yaml`. 

Here's the values.yaml I passed to helm on both install and upgrade:

```
env:
  open:
    STORAGE: microsoft
    STORAGE_MICROSOFT_CONTAINER: chartmuseum
    # prefix to store charts for microsoft storage backend
    STORAGE_MICROSOFT_PREFIX:
  secret:
    AZURE_STORAGE_ACCOUNT: "REDACTED" ## azure storage account
    AZURE_STORAGE_ACCESS_KEY: "REDACTED" ## azure storage account access key
    BASIC_AUTH_USER: REDACTED
    BASIC_AUTH_PASS: REDACTED

ingress:
  enabled: true
  hosts:
  - name: REDACTED
    path: /
    tls: true
    tlsSecret: tls-chartmuseum
```
