### ISSUE TITLE
Duplicate versions for same chart

### ISSUE THREAD

**Issue by hobti01** [helm/chartmuseum#450]
We are seeing many duplicate entries in `index.yaml` for the same chart version.  In some cases there are thousands of duplicates for the same version.  We expect only one entry per version/tag.

ChartMuseum version: 0.13.1
Running as part of Harbor with multiple instances of chartmuseum and settings:
```
ALLOW_OVERWRITE=true
CACHE: redis
DISABLE_STATEFILES: "false"
STORAGE: amazon
```

Is there a concurrency issue that we should be aware of?

Example:
```
  - apiVersion: v1
    created: "2021-04-10T14:59:57.826535265Z"
    digest: 1cd815901d2166307de13a7632ae04c053256863e486276c3411b26f7a3b2f0c
    name: ourrepo
    urls:
    - charts/ourrepo-0.0.0-84ace941.tgz
    version: 0.0.0-84ace941
  - apiVersion: v1
    created: "2021-04-19T08:59:10.291630412Z"
    digest: 1cd815901d2166307de13a7632ae04c053256863e486276c3411b26f7a3b2f0c
    name: ourrepo
    urls:
    - charts/ourrepo-0.0.0-84ace941.tgz
    version: 0.0.0-84ace941
```
