### ISSUE TITLE
helm search repo doesn't return any charts

### ISSUE THREAD

**Issue by Matroxt** [helm/chartmuseum#458]
helm version: `version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}`

Chartmuseum: tried both `0.13.1` and `0.12.0`, installed via the Chartmuseum Helm chart, hosted on GKE
Using Google Cloud Storage. The deployment is behind an ingress controller that takes care of TLS for my domain.

```
      - args:
        - --port=8080
        - --disable-statefiles
        - --chart-url=https://myrepo.domain/
        env:
        - name: DEBUG
          value: "true"
        - name: DISABLE_API
          value: "false"
        - name: DISABLE_METRICS
          value: "true"
        - name: LOG_JSON
          value: "true"
        - name: STORAGE
          value: google
        - name: STORAGE_GOOGLE_BUCKET
          value: my-bucket
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /config/service-account.json
        - name: BASIC_AUTH_PASS
          valueFrom:
            secretKeyRef:
              key: BASIC_AUTH_PASS
              name: chartmuseum
        - name: BASIC_AUTH_USER
          valueFrom:
            secretKeyRef:
              key: BASIC_AUTH_USER
              name: chartmuseum
```

I pushed a chart with Curl, it is detected by Chartmuseum and `index.yaml` picked it up as expected.

I added the repo like so:
`helm repo add myrepo https://myrepo.domain  --debug --username user --password pass`
It works, I also see the call for `/index.yaml` in Chartmuseum logs

However, `helm search repo myrepo --debug` return this with no charts:
```
search_repo.go:130: [debug] Original chart version: ""
search_repo.go:140: [debug] setting version to >0.0.0
No results found
```

But when I download `index.yaml` manually, I see my charts and I can download them via `/charts/mychart-version.tgz` (with basic auth)

Am I missing something obvious?

**Comment by scbizu** [comment]
maybe `helm repo update` required ?

**Comment by Matroxt** [comment]
I did run `helm repo update`
The output lets me believe that it worked:
```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "myrepo" chart repository
Update Complete. ⎈Happy Helming!⎈
```

Chartmuseum logs shows that it sees my charts, and that it's serving `index.yaml` when I run `helm repo update`
```
{"L":"INFO","T":"2021-05-20T02:31:52.720Z","M":"Rebuilding index for all tenants in cache"}
{"L":"INFO","T":"2021-05-20T02:31:52.720Z","M":"Rebuilding index for tenant","repo":""}
{"L":"DEBUG","T":"2021-05-20T02:31:52.720Z","M":"Entry found in cache store","repo":""}
{"L":"DEBUG","T":"2021-05-20T02:31:52.720Z","M":"Fetching chart list from storage","repo":""}
{"L":"DEBUG","T":"2021-05-20T02:31:52.767Z","M":"GetObject From Storage Backend","repo":"","path":"wallarm-ingress-2.16.0-5.tgz"}
{"L":"DEBUG","T":"2021-05-20T02:31:52.822Z","M":"GetObject From Storage Backend","repo":"","path":"wallarm-ingress-2.18.1-7.tgz"}
{"L":"DEBUG","T":"2021-05-20T02:31:52.871Z","M":"No change detected between cache and storage","repo":""}
{"L":"DEBUG","T":"2021-05-20T02:32:05.251Z","M":"[17053] Incoming request: /index.yaml","reqID":"750646xxfa"}
{"L":"DEBUG","T":"2021-05-20T02:32:05.251Z","M":"[17053] Entry found in cache store","repo":"","reqID":"750646xxfa"}
{"L":"INFO","T":"2021-05-20T02:32:05.251Z","M":"[17053] Request served","path":"/index.yaml","comment":"","clientIP":"MYIP","method":"GET","statusCode":200,"latency":"58.865µs","reqID":"750646xxfa"}
```

When I download index.yaml, I see my charts
```yaml
apiVersion: v1
entries:
  wallarm-ingress:
  - apiVersion: v1
    ...stuff...
    name: wallarm-ingress
    sources:
    - https://github.com/wallarm/ingress-chart
    urls:
    - https://myrepo.domain/charts/wallarm-ingress-2.18.1-7.tgz
    version: 2.18.1-7
  - apiVersion: v1
    appVersion: 2.16.0-5
    ...stuff...
    urls:
    - https://myrepo.domain/charts/wallarm-ingress-2.16.0-5.tgz
    version: 2.16.0-5
generated: "2021-05-19T02:52:53Z"
serverInfo: {}
```

But `helm search repo myrepo/` still returns nothing
I tried clearing my `HELM_REPOSITORY_CACHE` and `HELM_REPOSITORY_CONFIG` directory, but that didn't do much

The only thing that makes me wonder is the `"repo":""` is see in the logs (the string is empty), but I figured it's normal since I'm running with `depth=0` and I don't _think_ that impacts my local helm..

So yeah I'm a bit lost
