### ISSUE TITLE
Error saving index-cache.yaml

### ISSUE THREAD

**Issue by Goend** [helm/chartmuseum#644]
```
{"L":"WARN","T":"2022-11-22T10:26:47.756Z","M":"[177] Invalid package in storage","repo":"","action":"added","package":"tag-crd-6.0.1.tgz","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"WARN","T":"2022-11-22T10:26:47.756Z","M":"[177] Invalid package in storage","repo":"","action":"added","package":"proton-6.1.1.tgz","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"WARN","T":"2022-11-22T10:26:47.756Z","M":"[177] Invalid package in storage","repo":"","action":"added","package":"tag-crd-6.0.2.tgz","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"WARN","T":"2022-11-22T10:26:47.752Z","M":"[177] Invalid package in storage","repo":"","action":"added","package":"ceilometer-6.0.1.tgz","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"WARN","T":"2022-11-22T10:26:47.752Z","M":"[177] Invalid package in storage","repo":"","action":"added","package":"chartmuseum-6.0.1.tgz","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"WARN","T":"2022-11-22T10:26:47.756Z","M":"[177] Invalid package in storage","repo":"","action":"added","package":"grafana-6.1.1.tgz","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"WARN","T":"2022-11-22T10:26:47.752Z","M":"[177] Invalid package in storage","repo":"","action":"added","package":"magnum-5.0.3.tgz","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"WARN","T":"2022-11-22T10:26:47.756Z","M":"[177] Invalid package in storage","repo":"","action":"added","package":"glance-6.0.3.tgz","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"WARN","T":"2022-11-22T10:26:47.756Z","M":"[177] Invalid package in storage","repo":"","action":"added","package":"rbdmirror-6.2.1-alpha.159.tgz","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"WARN","T":"2022-11-22T10:26:47.756Z","M":"[177] Invalid package in storage","repo":"","action":"added","package":"rabbitmq-6.0.2.tgz","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"WARN","T":"2022-11-22T10:26:47.756Z","M":"[177] Invalid package in storage","repo":"","action":"added","package":"redis-6.0.1.tgz","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"WARN","T":"2022-11-22T10:26:47.756Z","M":"[177] Invalid package in storage","repo":"","action":"added","package":"grafana-6.0.1.tgz","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"DEBUG","T":"2022-11-22T10:26:47.757Z","M":"[177] index.yaml regenerated","repo":"","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"DEBUG","T":"2022-11-22T10:26:47.757Z","M":"[177] Entry saved in cache store","repo":"","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"INFO","T":"2022-11-22T10:26:47.757Z","M":"[177] Request served","path":"/index.yaml","comment":"","clientIP":"10.232.2.1","method":"GET","statusCode":200,"latency":"6.995884ms","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"WARN","T":"2022-11-22T10:26:47.757Z","M":"[177] Error saving index-cache.yaml","repo":"","error":"open /storage/default/index-cache.yaml: permission denied","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}
{"L":"DEBUG","T":"2022-11-22T10:26:47.758Z","M":"[177] index-cache.yaml saved in storage","repo":"","reqID":"b9bd4a99-9740-4a8a-9741-99170a9d03df"}

```
```
spec:
  containers:
  - args:
    - --port=8090
    - --storage=local
    - --storage-local-rootdir=/storage/default
    - --debug
    env:
    - name: AUTH_MODE
      value: None
    - name: CHART_POST_FORM_FIELD_NAME
      value: chart
    - name: DISABLE_METRICS
      value: "true"
    - name: LOG_JSON
      value: "true"
    - name: PROV_POST_FORM_FIELD_NAME
      value: prov
    - name: STORAGE
      value: local

```
```
    - mountPath: /storage
      name: storage-volume

  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: storage-volume-chartmuseum-0

```
