### ISSUE TITLE
Oracle Object Storage not working

### ISSUE THREAD

**Issue by raackley** [helm/chartmuseum#647]
I can not get Oracle Object Storage working.  When I try, I get the following error.

```
panic: can not create client, bad configuration: did not find a proper configuration for tenancy

goroutine 1 [running]:
github.com/chartmuseum/storage.NewOracleCSBackend({0x4000052046, 0xd}, {0x4000052076, 0xb}, {0x0, 0x0}, {0x400005a01d, 0x53})
	/home/runner/work/chartmuseum/chartmuseum/vendor/github.com/chartmuseum/storage/oracle.go:68 +0x57c
main.oracleBackendFromConfig(0x40003d31e8)
	/home/runner/work/chartmuseum/chartmuseum/cmd/chartmuseum/main.go:199 +0x170
main.backendFromConfig(0x40003d31e8)
	/home/runner/work/chartmuseum/chartmuseum/cmd/chartmuseum/main.go:145 +0x1f4
main.cliHandler(0x400090c420)
	/home/runner/work/chartmuseum/chartmuseum/cmd/chartmuseum/main.go:74 +0x1e0
github.com/urfave/cli.HandleAction({0x1969420, 0x1e5bbf0}, 0x400090c420)
	/home/runner/work/chartmuseum/chartmuseum/vendor/github.com/urfave/cli/app.go:526 +0x60
github.com/urfave/cli.(*App).Run(0x40001b9500, {0x400004c040, 0x2, 0x2})
	/home/runner/work/chartmuseum/chartmuseum/vendor/github.com/urfave/cli/app.go:286 +0x560
main.main()
	/home/runner/work/chartmuseum/chartmuseum/cmd/chartmuseum/main.go:54 +0x228
```

I am setting the following helm values, as instructed in the docs (with redactions).

```
  helm:
    parameters:
      - name: env.secret.BASIC_AUTH_PASS
        value: [redacted]
      - name: env.secret.BASIC_AUTH_USER
        value: [redacted]
      - name: env.open.DISABLE_API
        value: 'false'
      - name: env.open.AUTH_ANONYMOUS_GET
        value: 'true'
      - name: env.open.STORAGE
        value: oracle
      - name: env.open.STORAGE_ORACLE_BUCKET
        value: [redacted]
      - name: env.open.STORAGE_ORACLE_PREFIX
        value: chartmuseum
      - name: env.open.STORAGE_ORACLE_COMPARTMENTID
        value: >-
          ocid1.compartment.oc1..aaaaaaaa[redacted]...
      - name: oracle.secret.enabled
        value: 'true'
      - name: oracle.secret.name
        value: chartmuseum-secret
```

I've created the secret called `chartmuseum-secret` where the config data looks like the following and the key_file is the private key.

```
[DEFAULT]
user=ocid1.user.oc1..aaaaaaaa[redacted]...
fingerprint=b0:53:[redacted]...
tenancy=ocid1.tenancy.oc1..aaaaaaaa[redacted]...
region=us-ashburn-1
key_file=/home/chartmuseum/.oci/oci.key
```

I can create a new bucket in the compartment with the credentials provided no problem using the oci cli.  Am I doing something wrong with the chart configuration, or is this just busted?
