### ISSUE TITLE
NoCredentialProviders: no valid providers in chain. Deprecated

### ISSUE THREAD

**Issue by wonderphil** [helm/chartmuseum#709]
Hi guys,

I am sure this is just a miss config on my part so sorry in advance.  I am trying to run chartmuseum on my k8 cluster using minio s3 as my backend.  Minio is using lets-encrypt certs and is showing as trusted when I go to the endpoint.

I am using chart version 3.10.1

My values file is:

```
env:
  open:
    # storage backend, can be one of: local, alibaba, amazon, google, microsoft, oracle
    STORAGE: amazon
    # s3 bucket to store charts for amazon storage backend
    STORAGE_AMAZON_BUCKET: chartmuseum-staging
    # region of s3 bucket to store charts
    STORAGE_AMAZON_REGION: eu-london-1
    # alternative s3 endpoint
    STORAGE_AMAZON_ENDPOINT: https://s3.mydomain.io/

    DEBUG: true
    # enable Prometheus metrics
    ENABLE_METRICS: true
    # disable all routes prefixed with /api
    DISABLE_API: false
    # allow chart versions to be re-uploaded
    ALLOW_OVERWRITE: true
    existingSecret: chartmuseum-secret
    existingSecretMappings:
      AWS_ACCESS_KEY_ID: aws-access-key
      AWS_SECRET_ACCESS_KEY: aws-secret-access-key
      BASIC_AUTH_USER: basic-auth-user
      BASIC_AUTH_PASS: basic-auth-pass
```

My secret is:

```
apiVersion: v1
kind: Secret
metadata:
  name: chartmuseum-secret
  namespace: chartmuseum
data:
  aws-access-key: <base64encoded access key>
  aws-secret-access-key: <base64 encoded secret key>
  basic-auth-pass: bXlwYXNzd29yZA==
  basic-auth-user: Y3VyYXRvcg==
type: Opaque
```

And the only logs from my pods are:

```
{"L":"DEBUG","T":"2023-08-03T12:51:55.865Z","M":"Fetching chart list from storage","repo":""}
{"L":"ERROR","T":"2023-08-03T12:52:08.484Z","M":"NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors","repo":""}
2023/08/03 12:52:08 NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

While the pod is up I am able to console to it and print env and get this:
![Screenshot 2023-08-03 at 10 43 21 pm](https://github.com/helm/chartmuseum/assets/1829205/63f39d23-fa97-4cfc-a2ac-a22f1a1d388c)

Is it just me or am I missing something really simple?  I should also so the access keys I am using have full control over everything (just while testing) so should be a permissions issue.
